# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
#  cache:
#    type: CAFFEINE #指定cache类型
#    cache-names:
#      - getPersonById
#      - name2
#    caffeine:
#      spec: maximumSize=500,expireAfterWrite=5s
      
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)

  mail:
    host: smtp.exmail.qq.com
    username: service@mail.cn
    password: myPassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
    
server:
  port: 8082
management:
  port: 54001
  health:
    mail:
      enabled: false
info:
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
      
---
# 开发环境配置
spring:
  profiles: dev
  redis:
    cluster:
      nodes:
        - 192.168.0.17:6390
        - 192.168.0.17:6391
        - 192.168.0.17:6392
        - 192.168.0.9:6390
        - 192.168.0.9:6391
        - 192.168.0.9:6392
  datasource:
    url: jdbc:mysql://localhost:3306/
  data:
    mongodb:
      uri: mongodb://192.168.0.9:27017/test

myProps: #自定义的属性和值
  simpleProp: simplePropValue
  arrayProps: 1,2,3,4,5
  listProp1:
    - name: abc
      value: abcValue
    - name: efg
      value: efgValue
  listProp2:
    - config2Value1
    - config2Vavlue2
  mapProps:
    key1: value1
    key2: value2
  
---
# 测试环境配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.0.12:3306/
  
---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.0.13:3306/