spring:
  profiles:
    active: dev
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/?serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)

mybatis:
  mapperLocations: classpath:mapper/*.xml

#server:
#  port: 8083
logging:
  level:
    com:
      xjj: trace
